# Generated by Django 3.2.3 on 2021-06-07 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='achievment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a1', models.BooleanField(default=False)),
                ('a2', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id_p', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('CV', models.FileField(blank=True, upload_to='CV')),
                ('domaine', models.CharField(max_length=50)),
                ('XP', models.PositiveIntegerField(default=0)),
                ('sal', models.IntegerField(blank=True, help_text='the salary in $', null=True, verbose_name='salary')),
                ('achievment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='profileEmp.achievment')),
            ],
        ),
    ]
