# Generated by Django 3.2.3 on 2021-06-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileEmp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sal',
            field=models.FloatField(help_text='the salary in $', null=True, verbose_name='salary'),
        ),
    ]
