# Generated by Django 3.2.3 on 2021-06-14 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileEmp', '0003_auto_20210613_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='achievment',
        ),
        migrations.AddField(
            model_name='achievment',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='profileEmp.profile'),
        ),
    ]
