# Generated by Django 3.2.3 on 2021-06-14 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileEmp', '0004_auto_20210614_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievment',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ach', to='profileEmp.profile'),
        ),
    ]
