# Generated by Django 3.2.3 on 2021-06-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileEmp', '0005_alter_achievment_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievment',
            old_name='a1',
            new_name='D300xp',
        ),
        migrations.RenameField(
            model_name='achievment',
            old_name='a2',
            new_name='Do300xp',
        ),
        migrations.AddField(
            model_name='achievment',
            name='I300xp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievment',
            name='NoCancel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='achievment',
            name='Pr300xp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievment',
            name='Story1000',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievment',
            name='T300xp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievment',
            name='Task1000',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievment',
            name='m300xp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievment',
            name='project50',
            field=models.BooleanField(default=False),
        ),
    ]
