# Generated by Django 3.2.3 on 2021-06-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytask', '0002_alter_story_task_nv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story_task',
            name='strat_after_tasks',
            field=models.ManyToManyField(blank=True, to='storytask.Story_task'),
        ),
    ]
