# Generated by Django 3.2.3 on 2021-06-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storytask', '0003_alter_story_task_strat_after_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='story_task',
            name='date_create',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
