# Generated by Django 3.2.3 on 2021-06-15 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id_pj', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('type', models.CharField(choices=[('I', 'Interne'), ('E', 'Externe'), ('Ed', 'Educatif'), ('Ot', 'other')], max_length=3)),
                ('secteur', models.CharField(choices=[('RS', 'reseausociale'), ('Blog', 'Bolg'), ('E-com', 'e-commerce'), ('VG', 'Video-games'), ('AI', 'Artificial intelligence'), ('onS', 'online-services'), ('dig', 'digitalisation'), ('Ot', 'other')], max_length=5)),
                ('Device', models.CharField(choices=[('Mo', 'Mobile'), ('Web', 'Web'), ('De', 'desktop'), ('Se', 'serveur'), ('Em', 'Embedded system'), ('Ot', 'other')], max_length=3)),
                ('budget', models.FloatField(help_text='the salary in $')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('date_limit', models.DateField(blank=True, null=True)),
                ('create_date', models.DateField(auto_now_add=True, null=True)),
                ('update_date', models.DateField(blank=True, null=True)),
                ('archieve', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
