# Generated by Django 3.2.3 on 2021-06-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
